version: 2
jobs:
  docker_checkout_build_push:
    docker:
      - image: circleci/node:12-stretch
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: test and lint
          command: |
            sudo apt-get install -y expect
            cat > ../npm_login_expect <<EOF
            #!/usr/bin/expect -f
            set i 0; foreach n \$argv {set "p[incr i]" \$n}
            set timeout 60
            spawn npm login
            match_max 100000
            expect "Username"
            send "\$p1\r"
            expect "Password"
            send "\$p2\r"
            expect "Email"
            send "\$p3\r"
            expect {
              timeout      exit 1
              eof
            }
            EOF
            npm set registry ${NPM_REGISTRY}
            expect -f ../npm_login_expect $NPM_USER $NPM_PASS "$NPM_EMAIL"
            npm install
      - run:
          name: Login to docker registry
          command: |
            docker login -u ${DOCKER_REGISTRY_USER} -p ${DOCKER_REGISTRY_PWD} ${DOCKER_REGISTRY}
      - run:
          name: Build application Docker image
          command: |
            docker build --build-arg NPM_USER=${NPM_USER} --build-arg NPM_PASS=${NPM_PASS} --build-arg NPM_EMAIL=${NPM_EMAIL} --build-arg NPM_REGISTRY=${NPM_REGISTRY} -t app .
      - deploy:
          name: Push application Docker image
          command: |
            docker tag app ${DOCKER_REGISTRY}/library/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}
            docker tag app ${DOCKER_REGISTRY}/library/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}
            docker tag app ${DOCKER_REGISTRY}/library/${CIRCLE_PROJECT_REPONAME}:latest
            docker push ${DOCKER_REGISTRY}/library/${CIRCLE_PROJECT_REPONAME}
workflows:
  version: 2
  build:
    jobs:
      - docker_checkout_build_push:
          context: cognitant
          filters:
            branches:
              only:
                - master
                - integration
